parserOptions:
  ecmaVersion: 6
  sourceType: script
  ecmaFeatures:
    impliedStrict: no
    jsx: no
env:
  browser: no
  node: yes
  commonjs: yes
  es6: yes
extends: "eslint:recommended"
rules:
  comma-dangle:
    - error
    - always-multiline
  semi: error
